language: php
php:
  - 7.2
  - 7.3
  - 7.4
sudo: false
services:
  - mysql
before_install:
  - if [ $TRAVIS_PHP_VERSION == '7.2' ]; then phpenv config-rm xdebug.ini; fi;
  - mysql -e 'create database fusio;'
install:
  - composer install
  - php bin/fusio install --no-interaction
before_script:
  - php bin/fusio deploy
  - php bin/fusio migration:migrate --connection=System --no-interaction
script:
  - vendor/bin/phpunit
