version: 1
scopes: ["services"]
methods:
  GET:
    public: true
    summary: "Get service"
    description: "Returns a specific service entry by Id"
    responses:
      200: Service
      500: Message
    action: "${dir.src}/actions/services/get_service.php"